application:
  title: @project.name@
  version: @project.version@

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?stringtype=unspecified
    username: ${DB_USER_NAME}
    password: ${DB_USER_PW}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      # The default value is 'embedded', which only works for in-memory databases.
      # Since we're using a 'non-embedded' database here, we now need to set this to 'always'.
      mode: never

server:
  port: 8095